CREATE TABLE EMPRESAS (
    EMP_NOME_FANTASIA VARCHAR(50),
    EMP_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    EMP_SITE VARCHAR(100),
    EMP_EMAIL VARCHAR(100),
    EMP_NUMERO VARCHAR(8),
    EMP_COMPLEMENTO VARCHAR(20),
    EMP_CNPJ VARCHAR(16) NOT NULL UNIQUE,
    EMP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_ATUACOES_ATU_ID INTEGER,
    FK_CEPS_CEP_ID INTEGER
);

CREATE TABLE ATUACOES (
    ATU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ATU_NOME VARCHAR(30) NOT NULL UNIQUE,
    FK_SETORES_SET_ID INTEGER
);

CREATE TABLE SETORES (
    SET_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SET_NOME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE CEPS (
    CEP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CEP_LOGRADOURO VARCHAR(100),
    CEP_BAIRRO VARCHAR(30),
    FK_CIDADES_CID_ID INTEGER
);

CREATE TABLE CIDADES (
    CID_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CID_ESTADO ENUM('AC','AL','AP','AM','BA','CE','DF','ES','GO','MA','MT','MS','MG','PA','PB','PR','PE''PI','RJ','RN','RS','RO','RR','SC','SP','SE','TO') NOT NULL,
    CID_NOME VARCHAR(30) NOT NULL
);

CREATE TABLE COLABORADORES (
    COL_NOME VARCHAR(100) NOT NULL,
    COL_EMAIL VARCHAR(100),
    COL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_EMPRESAS_EMP_ID INTEGER,
    FK_DEPARTAMENTOS_DEP_ID INTEGER,
    FK_CARGOS_CAR_ID INTEGER
);

CREATE TABLE CARGOS (
    CAR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CAR_NOME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE DEPARTAMENTOS (
    DEP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DEP_NOME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE EVENTOS (
    EVE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EVE_NOME VARCHAR(150) NOT NULL,
    EVE_DATA DATE NOT NULL,
    EVE_HORA TIME,
    EVE_CUSTO_TOTAL DECIMAL(10,2) NOT NULL
);

CREATE TABLE FORNECEDORES (
    FOR_SITE VARCHAR(100),
    FOR_EMAIL VARCHAR(100),
    FOR_NOME_FANTASIA VARCHAR(50),
    FOR_ENDERECO VARCHAR(50),
    FOR_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    FOR_CNPJ VARCHAR(16) NOT NULL,
    FOR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_CEPS_CEP_ID INTEGER
);

CREATE TABLE SERVICOS (
    SER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SER_NOME VARCHAR(100) NOT NULL UNIQUE,
    SER_CUSTO DECIMAL(10,2),
    FK_FORNECEDORES_FOR_ID INTEGER
);

CREATE TABLE EMP_TELEFONES (
    EMP_TELEFONES_PK INT AUTO_INCREMENT PRIMARY KEY,
    EMT_DDD INTEGER NOT NULL,
    EMT_NUMERO INTEGER NOT NULL,
    FK_EMP_ID INTEGER
);

CREATE TABLE COL_TELEFONES (
    COL_TELEFONES_PK INT AUTO_INCREMENT PRIMARY KEY,
    COL_DDD INTEGER NOT NULL,
    COL_NUMERO INTEGER NOT NULL,
    FK_COL_ID INTEGER
);

CREATE TABLE FOR_TELEFONES (
    FOR_TELEFONES_PK INT AUTO_INCREMENT PRIMARY KEY,
    FOR_NUMERO INTEGER NOT NULL,
    FOR_DDD INTEGER NOT NULL,
    FK_FOR_ID INTEGER
);

CREATE TABLE COLABORADORES_EVENTOS (
    FK_COLABORADORES_COL_ID INTEGER,
    FK_EVENTOS_EVE_ID INTEGER,
    CEV_ID INTEGER AUTO_INCREMENT PRIMARY KEY
);

CREATE TABLE SERVICOS_EVENTOS (
    FK_SERVICOS_SER_ID INTEGER,
    FK_EVENTOS_EVE_ID INTEGER,
    SVE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SVE_VALOR DECIMAL(10,2)
);
 
ALTER TABLE EMPRESAS ADD CONSTRAINT FK_EMPRESAS_2
    FOREIGN KEY (FK_EMP_TELEFONES_EMP_TELEFONES_PK)
    REFERENCES EMP_TELEFONES (EMP_TELEFONES_PK)
    ON DELETE NO ACTION;
 
ALTER TABLE EMPRESAS ADD CONSTRAINT FK_EMPRESAS_3
    FOREIGN KEY (FK_ATUACOES_ATU_ID)
    REFERENCES ATUACOES (ATU_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EMPRESAS ADD CONSTRAINT FK_EMPRESAS_4
    FOREIGN KEY (FK_CEPS_CEP_ID)
    REFERENCES CEPS (CEP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE ATUACOES ADD CONSTRAINT FK_ATUACOES_2
    FOREIGN KEY (FK_SETORES_SET_ID)
    REFERENCES SETORES (SET_ID)
    ON DELETE CASCADE;
 
ALTER TABLE CEPS ADD CONSTRAINT FK_CEPS_2
    FOREIGN KEY (FK_CIDADES_CID_ID)
    REFERENCES CIDADES (CID_ID)
    ON DELETE CASCADE;
 
ALTER TABLE COLABORADORES ADD CONSTRAINT FK_COLABORADORES_2
    FOREIGN KEY (FK_COL_TELEFONES_COL_TELEFONES_PK)
    REFERENCES COL_TELEFONES (COL_TELEFONES_PK)
    ON DELETE NO ACTION;
 
ALTER TABLE COLABORADORES ADD CONSTRAINT FK_COLABORADORES_3
    FOREIGN KEY (FK_EMPRESAS_EMP_ID)
    REFERENCES EMPRESAS (EMP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE COLABORADORES ADD CONSTRAINT FK_COLABORADORES_4
    FOREIGN KEY (FK_DEPARTAMENTOS_DEP_ID)
    REFERENCES DEPARTAMENTOS (DEP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE COLABORADORES ADD CONSTRAINT FK_COLABORADORES_5
    FOREIGN KEY (FK_CARGOS_CAR_ID)
    REFERENCES CARGOS (CAR_ID)
    ON DELETE CASCADE;
 
ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDORES_2
    FOREIGN KEY (FK_FOR_TELEFONES_FOR_TELEFONES_PK)
    REFERENCES FOR_TELEFONES (FOR_TELEFONES_PK)
    ON DELETE NO ACTION;
 
ALTER TABLE FORNECEDORES ADD CONSTRAINT FK_FORNECEDORES_3
    FOREIGN KEY (FK_CEPS_CEP_ID)
    REFERENCES CEPS (CEP_ID)
    ON DELETE CASCADE;
 
ALTER TABLE SERVICOS ADD CONSTRAINT FK_SERVICOS_2
    FOREIGN KEY (FK_FORNECEDORES_FOR_ID)
    REFERENCES FORNECEDORES (FOR_ID)
    ON DELETE CASCADE;
 
ALTER TABLE EMP_TELEFONES ADD CONSTRAINT FK_EMP_TELEFONES_2
    FOREIGN KEY (FK_EMP_ID)
    REFERENCES EMPRESAS (EMP_ID);
 
ALTER TABLE COL_TELEFONES ADD CONSTRAINT FK_COL_TELEFONES_2
    FOREIGN KEY (FK_COL_ID)
    REFERENCES COLABORADORES (COL_ID);
 
ALTER TABLE FOR_TELEFONES ADD CONSTRAINT FK_FOR_TELEFONES_2
    FOREIGN KEY (FK_FOR_ID)
    REFERENCES FORNECEDORES (FOR_ID);
 
ALTER TABLE COLABORADORES_EVENTOS ADD CONSTRAINT FK_COLABORADORES_EVENTOS_2
    FOREIGN KEY (FK_COLABORADORES_COL_ID)
    REFERENCES COLABORADORES (COL_ID)
    ON DELETE SET NULL;
 
ALTER TABLE COLABORADORES_EVENTOS ADD CONSTRAINT FK_COLABORADORES_EVENTOS_3
    FOREIGN KEY (FK_EVENTOS_EVE_ID)
    REFERENCES EVENTOS (EVE_ID)
    ON DELETE SET NULL;
 
ALTER TABLE SERVICOS_EVENTOS ADD CONSTRAINT FK_SERVICOS_EVENTOS_2
    FOREIGN KEY (FK_SERVICOS_SER_ID)
    REFERENCES SERVICOS (SER_ID)
    ON DELETE RESTRICT;
 
ALTER TABLE SERVICOS_EVENTOS ADD CONSTRAINT FK_SERVICOS_EVENTOS_3
    FOREIGN KEY (FK_EVENTOS_EVE_ID)
    REFERENCES EVENTOS (EVE_ID)
    ON DELETE SET NULL;
