DROP DATABASE IF EXISTS LBA2024;
CREATE DATABASE IF NOT EXISTS LBA2024;
USE LBA2024;

CREATE TABLE IF NOT EXISTS SETORES (
    SET_ID INTEGER AUTO_INCREMENT,
    SET_NOME VARCHAR(30) NOT NULL UNIQUE,
    PRIMARY KEY (SET_ID)
);

CREATE TABLE IF NOT EXISTS ATUACOES (
    ATU_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ATU_NOME VARCHAR(30) NOT NULL UNIQUE,
    FK_SETORES_SET_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_SETORES_SET_ID)
        REFERENCES SETORES (SET_ID)
);

CREATE TABLE IF NOT EXISTS CIDADES (
    CID_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CID_ESTADO ENUM('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO') NOT NULL,
    CID_NOME VARCHAR(30) NOT NULL,
    UNIQUE (CID_ESTADO , CID_NOME)
);

CREATE TABLE IF NOT EXISTS CEPS (
    CEP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CEP_LOGRADOURO VARCHAR(100) NOT NULL,
    CEP_BAIRRO VARCHAR(30) NOT NULL,
    FK_CIDADES_CID_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CIDADES_CID_ID)
        REFERENCES CIDADES (CID_ID)
);

CREATE TABLE IF NOT EXISTS EMPRESAS (
    EMP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMP_NOME_FANTASIA VARCHAR(50),
    EMP_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    EMP_SITE VARCHAR(100),
    EMP_EMAIL VARCHAR(100),
    EMP_NUMERO VARCHAR(8),
    EMP_COMPLEMENTO VARCHAR(20),
    EMP_CNPJ VARCHAR(16) NOT NULL UNIQUE,
    FK_ATUACOES_ATU_ID INTEGER NOT NULL,
    FK_CEPS_CEP_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_ATUACOES_ATU_ID)
        REFERENCES ATUACOES (ATU_ID),
    FOREIGN KEY (FK_CEPS_CEP_ID)
        REFERENCES CEPS (CEP_ID)
);

CREATE TABLE IF NOT EXISTS TELEFONES_EMPRESAS (
    TLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    TLE_DDD INTEGER NOT NULL,
    TLE_NUMERO INTEGER NOT NULL,
    FK_EMP_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_EMP_ID)
        REFERENCES EMPRESAS (EMP_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS CARGOS (
    CAR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    CAR_NOME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS DEPARTAMENTOS (
    DEP_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    DEP_NOME VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS COLABORADORES (
    COL_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    COL_NOME VARCHAR(100) NOT NULL,
    COL_EMAIL VARCHAR(100),
    FK_EMPRESAS_EMP_ID INTEGER NOT NULL,
    FK_DEPARTAMENTOS_DEP_ID INTEGER NOT NULL,
    FK_CARGOS_CAR_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_EMPRESAS_EMP_ID)
        REFERENCES EMPRESAS (EMP_ID),
    FOREIGN KEY (FK_DEPARTAMENTOS_DEP_ID)
        REFERENCES DEPARTAMENTOS (DEP_ID),
    FOREIGN KEY (FK_CARGOS_CAR_ID)
        REFERENCES CARGOS (CAR_ID)
);

CREATE TABLE IF NOT EXISTS TELEFONES_COLABORADORES (
    TLC_ID INT AUTO_INCREMENT PRIMARY KEY,
    TLC_DDD INTEGER NOT NULL,
    TLC_NUMERO INTEGER NOT NULL,
    FK_COL_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_COL_ID)
        REFERENCES COLABORADORES (COL_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS FORNECEDORES (
    FOR_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FOR_SITE VARCHAR(100),
    FOR_EMAIL VARCHAR(100),
    FOR_NOME_FANTASIA VARCHAR(50),
    FOR_RAZAO_SOCIAL VARCHAR(100) NOT NULL,
    FOR_CNPJ VARCHAR(16) NOT NULL UNIQUE,
    FK_CEPS_CEP_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_CEPS_CEP_ID)
        REFERENCES CEPS (CEP_ID)
);

CREATE TABLE IF NOT EXISTS TELEFONES_FORNECEDORES (
    TLF_ID INT AUTO_INCREMENT PRIMARY KEY,
    TLF_NUMERO INTEGER NOT NULL,
    TLF_DDD INTEGER NOT NULL,
    FK_FOR_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_FOR_ID)
        REFERENCES FORNECEDORES (FOR_ID)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SERVICOS (
    SER_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SER_NOME VARCHAR(100) NOT NULL,
    SER_CUSTO DECIMAL(10 , 2 ) NOT NULL,
    FK_FORNECEDORES_FOR_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_FORNECEDORES_FOR_ID)
        REFERENCES FORNECEDORES (FOR_ID)
);


CREATE TABLE IF NOT EXISTS EVENTOS (
    EVE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EVE_NOME VARCHAR(150) NOT NULL,
    EVE_DATA DATE NOT NULL,
    EVE_HORA TIME NOT NULL,
    EVE_CUSTO_TOTAL DECIMAL(10 , 2 ) NOT NULL DEFAULT 0.0
);

CREATE TABLE IF NOT EXISTS SERVICOS_EVENTOS (
    SVE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    SVE_VALOR DECIMAL(10 , 2 ) NOT NULL,
    FK_SERVICOS_SER_ID INTEGER NOT NULL,
    FK_EVENTOS_EVE_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_SERVICOS_SER_ID)
        REFERENCES SERVICOS (SER_ID),
    FOREIGN KEY (FK_EVENTOS_EVE_ID)
        REFERENCES EVENTOS (EVE_ID)
);
 
CREATE TABLE IF NOT EXISTS COLABORADORES_EVENTOS (
    CEV_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FK_COLABORADORES_COL_ID INTEGER NOT NULL,
    FK_EVENTOS_EVE_ID INTEGER NOT NULL,
    FOREIGN KEY (FK_COLABORADORES_COL_ID)
        REFERENCES COLABORADORES (COL_ID),
    FOREIGN KEY (FK_EVENTOS_EVE_ID)
        REFERENCES EVENTOS (EVE_ID)
);

INSERT INTO SETORES (SET_NOME) VALUES ("Música e Shows"), ("eSports"), ("Produção Audiovisual");

INSERT INTO ATUACOES (ATU_NOME, FK_SETORES_SET_ID)  VALUES ("Produção Musical", 1), ("Organização de Torneios", 2), ("Animação e Efeitos Visuais", 3);

INSERT INTO CIDADES (CID_ESTADO, CID_NOME) VALUES ("SP", "Tietê"), ("SP", "Mococa"), ("SP", "São João da Boa Vista");

INSERT INTO CEPS (CEP_LOGRADOURO, CEP_BAIRRO, FK_CIDADES_CID_ID) VALUES ("Rua Francisco Costa, 325", "Jardim Bonanza", 1), ("Rua João Falarini, 20", "Vila Carvalho", 2), ("Rua Dom Pedro II, 14a", "Vila Carvalho", 3);

INSERT INTO FORNECEDORES (FOR_SITE, FOR_EMAIL, FOR_NOME_FANTASIA, FOR_RAZAO_SOCIAL, FOR_CNPJ, FK_CEPS_CEP_ID) 
VALUES 
("www.sonoprod.com", "contato@sonoprod.com", "SonoProd", "Sono Produções Ltda", "45678901000133", 1),
("www.gamingsupply.com", "info@gamingsupply.com", "Gaming Supply", "Gaming Supplies Ltda", "56789012000144", 2),
("www.vfxlab.com", "support@vfxlab.com", "VFX Lab", "VFX Laboratório de Animação Ltda", "67890123000155", 3);

INSERT INTO TELEFONES_FORNECEDORES (TLF_NUMERO, TLF_DDD, FK_FOR_ID) 
VALUES 
(32144567, 11, 1),
(33226789, 19, 2),
(30987654, 31, 3);

INSERT INTO SERVICOS (SER_NOME, SER_CUSTO, FK_FORNECEDORES_FOR_ID) 
VALUES 
("Aluguel de Equipamento de Som", 500.00, 1),
("Fornecimento de PCs para Torneios", 1500.00, 2),
("Animação 3D para Comerciais", 2000.00, 3);

INSERT INTO EVENTOS (EVE_NOME, EVE_DATA, EVE_HORA, EVE_CUSTO_TOTAL) 
VALUES 
("Festival de Música Mococa", '2024-11-15', '18:00:00', 10000.00),
("Campeonato de eSports Brasil", '2024-12-10', '10:00:00', 20000.00),
("Mostra de Animação SP", '2025-01-20', '14:00:00', 15000.00);

INSERT INTO SERVICOS_EVENTOS (SVE_VALOR, FK_SERVICOS_SER_ID, FK_EVENTOS_EVE_ID) 
VALUES 
(500.00, 1, 1),
(1500.00, 2, 2),
(2000.00, 3, 3);

INSERT INTO EMPRESAS (EMP_NOME_FANTASIA, EMP_RAZAO_SOCIAL, EMP_SITE, EMP_EMAIL, EMP_NUMERO, EMP_COMPLEMENTO, EMP_CNPJ, FK_ATUACOES_ATU_ID, FK_CEPS_CEP_ID) 
VALUES 
("Mococa Shows", "Mococa Produções Artísticas Ltda", "www.mococashows.com.br", "contato@mococashows.com.br", "123", "Bloco A", "12345678000100", 1, 1),
("Gaming Brasil", "Gaming Eventos e Esportes Ltda", "www.gamingbrasil.com", "info@gamingbrasil.com", "456", "Sala 5", "23456789000111", 2, 2),
("Pixel Animation", "Pixel Produções Audiovisuais Ltda", "www.pixelanimation.com", "contact@pixelanimation.com", "789", "Andar 2", "34567890000122", 3, 3);

INSERT INTO TELEFONES_EMPRESAS (TLE_DDD, TLE_NUMERO, FK_EMP_ID) 
VALUES 
(11, 987654321, 1),
(19, 998877665, 2),
(31, 912345678, 3);

INSERT INTO CARGOS (CAR_NOME) 
VALUES 
("Gerente de Produção"), 
("Técnico de Som"), 
("Designer Gráfico");

INSERT INTO DEPARTAMENTOS (DEP_NOME) 
VALUES 
("Produção"), 
("Marketing"), 
("Financeiro");

INSERT INTO COLABORADORES (COL_NOME, COL_EMAIL, FK_EMPRESAS_EMP_ID, FK_DEPARTAMENTOS_DEP_ID, FK_CARGOS_CAR_ID) 
VALUES 
("Carlos Silva", "carlos.silva@mococashows.com.br", 1, 1, 1),
("Ana Souza", "ana.souza@gamingbrasil.com", 2, 2, 2),
("Bruno Pereira", "bruno.pereira@pixelanimation.com", 3, 3, 3);

INSERT INTO TELEFONES_COLABORADORES (TLC_DDD, TLC_NUMERO, FK_COL_ID) 
VALUES 
(11, 995544332, 1),
(19, 996677889, 2),
(31, 993344556, 3);

INSERT INTO COLABORADORES_EVENTOS (FK_COLABORADORES_COL_ID, FK_EVENTOS_EVE_ID) 
VALUES 
(1, 1),
(2, 2),
(3, 3);

UPDATE CEPS 
SET CEP_BAIRRO = 'Jardim Ypê'
WHERE CEP_BAIRRO = 'Vila Ypê' 
AND CEP_ID BETWEEN 13876600 AND 13876609;

UPDATE EVENTOS
SET EVE_DATA = '2024-11-20'
WHERE EVE_DATA = '2024-11-10';

UPDATE COLABORADORES
SET FK_DEPARTAMENTOS_DEP_ID = 3, FK_CARGOS_CAR_ID = 1
WHERE COL_NOME = 'Ana Souza';

DELETE FROM COLABORADORES
WHERE COL_EMAIL LIKE '%@uol%';
