USE TEST;

SELECT CODIGO_CIDADE, NOME_CIDADE FROM CIDADES
WHERE NOME_CIDADE LIKE '%vista%'
ORDER BY NOME_CIDADE;

SELECT CODIGO_CIDADE, ESTADO, NOME_CIDADE FROM CIDADES
WHERE ESTADO IN ('SP', 'RJ', 'MG', 'ES')
ORDER BY ESTADO, NOME_CIDADE;

SELECT CODIGO_CIDADE, ESTADO, NOME_CIDADE, POPULACAO_TOTAL FROM CIDADES
WHERE POPULACAO_TOTAL > 1000000
ORDER BY POPULACAO_TOTAL DESC;

SELECT CODIGO_CIDADE, ESTADO, NOME_CIDADE, POPULACAO_TOTAL FROM CIDADES
WHERE POPULACAO_TOTAL BETWEEN 10000 AND 13000;

SELECT CODIGO_CIDADE, ESTADO, NOME_CIDADE, POPULACAO_TOTAL FROM CIDADES
ORDER BY POPULACAO_TOTAL DESC
LIMIT 10;

SELECT CODIGO_CIDADE, ESTADO, NOME_CIDADE, POPULACAO_TOTAL FROM CIDADES
ORDER BY POPULACAO_TOTAL DESC
LIMIT 10;
