SELECT NOME, CARGO, DEPARTAMENTO FROM FUNCIONARIO
UNION
SELECT NOME, CARGO, DEPARTAMENTO FROM FUNCIONARIO_BACKUP
ORDER BY DEPARTAMENTO, CARGO, NOME;

SELECT * FROM FUNCIONARIO
UNION ALL
SELECT * FROM FUNCIONARIO_BACKUP
ORDER BY ID_FUNCIONARIO;

SELECT * FROM FUNCIONARIO
UNION 
SELECT * FROM FUNCIONARIO_BACKUP
ORDER BY ID_FUNCIONARIO;
-- Sim, pois o UNION remove as duplicatas

SELECT ID_FUNCIONARIO, NOME, CARGO, DEPARTAMENTO FROM FUNCIONARIO
WHERE DEPARTAMENTO == "TI"
UNION
SELECT  ID_FUNCIONARIO, NOME, CARGO, DEPARTAMENTO FROM FUNCIONARIO_BACKUP
WHERE DEPARTAMENTO == "TI"
ORDER BY DEPARTAMENTO, CARGO, NOME;
